---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - JSON_PRETTIER
  - YAML_PRETTIER

MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD041
YAML_YAMLLINT_ARGUMENTS: --strict
