---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL
DISABLE_LINTERS:
  - JSON_PRETTIER
  - YAML_PRETTIER

GITHUB_COMMENT_REPORTER: true
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true

MARKDOWN_MARKDOWNLINT_ARGUMENTS: --disable MD041
REPOSITORY_KICS_DISABLE_ERRORS: true
YAML_YAMLLINT_ARGUMENTS: --strict
