# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

DISABLE:
  - SPELL
MARKDOWN_MARKDOWNLINT_ARGUMENTS: "--disable MD041"
