---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12:00

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    permissions:
      contents: read
    uses: daniel-mizsak/workflows/.github/workflows/prek.yml@ac5a2f72a00a396751fd59a43f69cad2bc72780f # v2.4.0

  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: daniel-mizsak/workflows/.github/workflows/lint.yml@ac5a2f72a00a396751fd59a43f69cad2bc72780f # v2.4.0
    with:
      megalinter-config: "./.github/linters/.megalinter.yml"
