---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12:00

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    permissions:
      contents: read
    uses: daniel-mizsak/workflows/.github/workflows/prek.yml@6fe0b2d7b995be2cf288f1603c769f0cbf26b239 # v2.2.0

  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: daniel-mizsak/workflows/.github/workflows/lint.yml@6fe0b2d7b995be2cf288f1603c769f0cbf26b239 # v2.2.0
    with:
      megalinter-config: "./.github/linters/.megalinter.yml"
