# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6"  # Every Saturday at 12:00

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4.2.2

      - name: Run megalinter
        uses: oxsecurity/megalinter/flavors/cupcake@v8.8.0
        env:
          MEGALINTER_CONFIG: .github/linters/.megalinter.yml
