---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 12 * * 6" # Every Saturday at 12:00

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prek:
    permissions:
      contents: read
    uses: daniel-mizsak/workflows/.github/workflows/prek.yml@5264b813cd3b482136d8e33ba9a1e69c2c4b0c64 # v2.0.0

  lint:
    permissions:
      contents: read
      pull-requests: write
    uses: daniel-mizsak/workflows/.github/workflows/lint.yml@5264b813cd3b482136d8e33ba9a1e69c2c4b0c64 # v2.0.0
    with:
      megalinter-config: "./.github/linters/.megalinter.yml"
